server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  elasticsearch:
    rest:
      uris: es-cn-mp91058pt0018q7kt.elasticsearch.aliyuncs.com
      port: 9200
      username: elastic
      password: elastic1!